---
- hosts: localhost  
  vars:
    app_name: lola
    app_user: ubuntu
    app_path: /home/{{app_user}}/{{app_name}}
    app_pyenv: "{{app_path}}/pyenv"
    app_runlevel: 2345  
  tasks:
  - name: Gather EC2 facts
    action: ec2_facts

  - name: Install OS common pre-requisites via APT
    action: apt pkg={{item}} state=latest
    with_items:
      - git
      - python
      - python-pip
      - python-virtualenv
      - python-dev
      - libyaml-cpp-dev
      - screen
      - nginx
    when: ansible_pkg_mgr == "apt"    

  - name: Copy the webapp files
    copy: src=webapp/ dest={{app_path}}   

  - name: Create the service virtualenv
    shell: virtualenv {{app_pyenv}} creates={{app_pyenv}}

  - name: Copy the requirements.txt to the env folder
    template: src=files/requirements.txt dest={{app_pyenv}}

  - name: Install requirements into the virtualenv
    pip:
      requirements={{app_pyenv}}/requirements.txt
      virtualenv={{app_pyenv}}

  - name: Add the uwsgi config to /etc/config
    template: src=files/lola.conf dest=/etc/init/lola.conf

  - name: Add the nginx conf to /etc/nginx/sites-available
    template: src=files/lola dest=/etc/nginx/sites-available/lola

  - name: Link conf from /etc/nginx/sites-available/ to /etc/nginx/sites-enabled
    file: src=/etc/nginx/sites-available/lola
          dest=/etc/nginx/sites-enabled/lola
          state=link

  - name: Change the owner of the app home to ubuntu:ubuntu
    file: path={{app_path}} owner={{app_user}} group={{app_user}}

  - name: (Re)Start the webapp process
    service: name=lola state=restarted

  - name: Restart nginx 
    service: name=nginx state=restarted
