- name: Gather EC2 facts
  action: ec2_facts #ec2_metadata_facts

- name: Install OS common pre-requisites via APT
  action: apt pkg={{item}} state=latest
  with_items:
    - git
    - python
    - python-pip
    - python-virtualenv
    - python-dev
    - python-mysqldb
    - libyaml-cpp-dev
    - screen
    - nginx
  when: ansible_pkg_mgr == "apt"    

- name: Copy the webapp files
  copy: src=webapp/ dest={{app_path}}   

- name: Create the service virtualenv
  shell: virtualenv {{app_pyenv}} creates={{app_pyenv}}

- name: Copy the requirements.txt to the env folder
  template: src=files/requirements.txt dest={{app_pyenv}}

- name: Install requirements into the virtualenv
  pip:
    requirements={{app_pyenv}}/requirements.txt
    virtualenv={{app_pyenv}}

- name: Add the uwsgi config to /etc/config
  template: src=files/{{app_name}}.conf dest=/etc/init/{{app_name}}.conf

- name: Add the nginx conf to /etc/nginx/sites-available
  template: src=files/{{app_name}} dest=/etc/nginx/sites-available/{{app_name}}
  
- name: Remove default nginx site
  file:
    path: /etc/nginx/sites-available/default
    state: absent

- name: Link conf from /etc/nginx/sites-available/ to /etc/nginx/sites-enabled
  file: src=/etc/nginx/sites-available/{{app_name}}
        dest=/etc/nginx/sites-enabled/{{app_name}}
        state=link

- name: Change the owner of the app home to ubuntu:ubuntu
  file: path={{app_path}} owner={{app_user}} group={{app_user}}

- name: (Re)Start the webapp process
  service: name={{app_name}} state=restarted

- name: Restart nginx 
  service: name=nginx state=restarted
